function about() {
    document.getElementById("body").innerHTML='<div class="environment"> <div class="enivronment_header"> <p class="centred_page_heading">Dom Hutchinson</p> </div> <div class="about_row"> <div class="experience_box" style="flex:1"></div> <div class="experience_box about_pic" style="flex:1; background-color: transparent"></div> </div> <div class="about_row"> <div class="experience_box" style="flex:1"></div> <div class="experience_box" style="flex:1"></div> <div class="experience_box" style="flex:1"></div> </div> </div>';
}

function qualifications() {
    document.getElementById("body").innerHTML='<!-- QUALIFCATION--> <p class="centred_page_heading">Qualifications</p> <div id="qualification_view_options"> <a class="centred_page_subheading" id="qual_overview_btn" onclick="qual_overview()" style="color:#122314;">Overview</a> <a class="centred_page_subheading" id="qual_timeline_btn" onclick="qual_timeline()">Timeline</a> </div> <div id="qualification_content"> <div style="display: flex"> <div class="experience_box" style="flex:1"> <h1>Masters</h1> <h2>MEng in Maths & CS</h2> <h2>In Progress</h2> <h2>University of Bristol</h2> <hr style="margin: 0 5%; border-top-color: lightgray"> <ul class="qual_overview_detail_ul"> <li>Year 1 - 77%</li> <li>Year 2 - 73%</li> <li>Year 3 - In Progess</li> <li>Year 4 - TODO</li> </ul> </div> <div class="experience_box" style="flex:1"> <h1>A-Levels</h1> <h2>3A* A</h2> <h2>Oundle School</h2> <hr style="margin: 0 5%; border-top-color: lightgray"> <ul class="qual_overview_detail_ul"> <li>Maths. - A*</li> <li>Further Maths. - A*</li> <li>Pre-U Physics - D2 (A*)</li> <li>Computer Science - A</li> </ul> </div> <div class="experience_box" style="flex:1"> <h1>GCSEs</h1> <h2>6A* 4A</h2> <h2>Oundle School</h2> <hr style="margin: 0 5%; border-top-color: lightgray"> <ul class="qual_overview_detail_ul"> <li>A* - Maths, English, Chemistry, Physics, Geography &amp; Computing</li> <li>A  - Biology, French, RS &amp; Latin</li> </ul> </div> <div class="experience_box" style="flex:1"> <h1>Other</h1> <hr style="margin: 0 5%; border-top-color: lightgray"> <ul class="qual_overview_detail_ul"> <li>DofE Gold - 2019</li> <li>DofE Silver - 2015</li> <li>DofE Bronze - 2013</li> <li>Major Academic Scholarship (Oundle School) - 2012</li> <li>5x School Computing Prize (2012-2017)</li> <li>UKMT Gold - 1x Senior, 3x Intermediate, 3x Junior</li> </ul> </div> </div> </div>';
}

function experience() {
    document.getElementById("body").innerHTML='<p class="centred_page_heading">Experience</p> <div style="display: flex"> <div class="experience_box" style="flex:1"> <h1>Barclays Bank</h1> <hr style="margin: 0 5%; border-top-color: lightgray"> <h2>2019</h2> <h2>Summer Internship</h2> <div class="centre_container"> <ul> <li>Ran a project to taxonomise &amp; document the technology landscape for Barclaycard Commercial Payments.</li> <li>Organised international panel on "Women in Tech - Role of a Male Ally".</li> </ul> </div> </div> <div class="experience_box" style="flex:1"> <h1>Gig Economy</h1> <hr style="margin: 0 5%; border-top-color: lightgray"> <h2>2018-Present</h2> <div class="centre_container"> <ul> <li>Dog Sitter &amp; Walker with <a class="company_anchor">Rover</a>.</li> <li>Cycle Courier with <a class="company_anchor">UberEATs</a> &amp; <a class="company_anchor">Stuart</a>.</li> <li>Warehouse worker &amp; Cycle Courier with <a class="company_anchor">8Dol</a>.</li> </ul> </div> </div> <div class="experience_box" style="flex:1"> <h1>Other</h1> <hr style="margin: 0 5%; border-top-color: lightgray"> <div class="centre_container"> <ul> <li>Tutoring GCSE Maths.</li> <li>Computer tutoring for children with learning difficulties.</li> <li>Helped in local library. Lead creative activities for children.</li> </ul> </div> </div> </div>';
}

function projects() {
    document.getElementById("body").innerHTML='<div class="environment"> <div class="environment_header"> <p class="centred_page_heading">Projects</p> </div> <div id="projects_content"> </div> <div id="project_footer"> <ul class="horizontal_scroll_list full no-scrollbar" style="height:50px"> <li class="projects_bar_item"><a class=".anchor_li_fill" onclick="project1();">Fitness</a></li> <li class="projects_bar_item"><a class=".anchor_li_fill" onclick="project2();">Betting</a></li> <li class="projects_bar_item"><a class=".anchor_li_fill" onclick="project3();"></a></li> <li class="projects_bar_item"><a class=".anchor_li_fill" onclick="project4();"></a></li> <li class="projects_bar_item"><a class=".anchor_li_fill" onclick="project5();"></a></li> </ul> </div> </div>';
}

function cover() {
    document.getElementById("body").innerHTML='<div class="cover_image"> <div style="padding-top: 40vh;"> <h1 class="cover_title">DOM HUTCHINSON</h1> </div> </div>';
}
